# Generated by Django 4.2.3 on 2023-07-10 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="due_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Data"
            ),
            preserve_default=False,
        ),
    ]
