# Generated by Django 4.2.3 on 2023-07-10 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("todo", "0002_item_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criador",
            ),
            preserve_default=False,
        ),
    ]
